name: "WordPress Host Test"
description: 

#
#    env:
      # This is only a subset/example of env vars available. See the `.env.default` file for a full list.
#      WPT_PREPARE_DIR: ${{ secrets.WPT_PREPARE_DIR }}
#      WPT_TEST_DIR: ${{ secrets.WPT_TEST_DIR }}
#      WPT_REPORT_API_KEY: ${{ secrets.WPT_REPORT_API_KEY }}
#      WPT_PHP_EXECUTABLE: ${{ secrets.WPT_PHP_EXECUTABLE }}
      # Database settings
#      WPT_DB_NAME: ${{ secrets.WPT_DB_NAME }}
#      WPT_DB_USER: ${{ secrets.WPT_DB_USER }}
#      WPT_DB_PASSWORD: ${{ secrets.WPT_DB_PASSWORD }}
#      WPT_DB_HOST: ${{ secrets.WPT_DB_HOST }}
      # SSH settings for connecting to the test environment.
 #     WPT_SSH_CONNECT: ${{ secrets.WPT_SSH_CONNECT }}
#      WPT_SSH_PRIVATE_KEY_BASE64: ${{ secrets.WPT_SSH_PRIVATE_KEY_BASE64 }}


inputs:
  report-api-key:
    required: false
  remote-test-dir:
    required: true
  database-host:
    required: true
  database-user:
    required: true
  database-password:
    required: true
  database-name:
    required: true
  ssh-connect:
    required: true
  ssh-private-key:
    required: true
runs:
  using: "composite"
  steps:  
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: WordPress/phpunit-test-runner
        path: runner

    - name: Set up PHP
      uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a # v2.33.0
      with:
        php-version: '8.4'
        coverage: none

    - name: Install NodeJS
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 20
    
    - name: Prepare SSH private key
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo '${{ inputs.ssh-private-key }}' | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Prepare environment
      env:
        WPT_PREPARE_DIR: /tmp/wp-tests
        WPT_TEST_DIR: ${{ inputs.remote-test-dir }}
        WPT_DB_NAME: ${{ inputs.database-name }}
        WPT_DB_USER: ${{ inputs.database-user }}
        WPT_DB_PASSWORD: ${{ inputs.database-password }}
        WPT_DB_HOST:  ${{ inputs.database-host }}
        WPT_SSH_CONNECT: ${{ inputs.ssh-connect }}
      run: php prepare.php
      shell: bash
      working-directory: ./runner

    - name: Run unit tests
      run: php test.php
      continue-on-error: true
      shell: bash
      working-directory: ./runner
      env:
        WPT_PREPARE_DIR: /tmp/wp-tests
        WPT_TEST_DIR: ${{ inputs.remote-test-dir }}
        WPT_DB_NAME: ${{ inputs.database-name }}
        WPT_DB_USER: ${{ inputs.database-user }}
        WPT_DB_PASSWORD: ${{ inputs.database-password }}
        WPT_DB_HOST:  ${{ inputs.database-host }}
        WPT_SSH_PRIVATE_KEY_BASE64: ${{ inputs.ssh-private-key }}
        WPT_SSH_CONNECT: ${{ inputs.ssh-connect }}

    - name: Report the results
      run: php report.php
      continue-on-error: true
      if: ${{ inputs.report-api-key }}
      shell: bash
      working-directory: ./runner
      env:
        WPT_REPORT_API_KEY: ${{ inputs.report-api-key }}

    - name: Cleanup
      run: php cleanup.php
      shell: bash
      working-directory: ./runner