name: Run WordPress Unit Tests
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  run-tests:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/wordpress-host-test
        with:
          ssh-connect: '${{ secrets.SSH_CONNECT }}'
          ssh-private-key: '${{ secrets.SSH_PRIVATE_KEY }}'
          remote-test-dir: /files/wordpress-host-test
          database-host: ${{ secrets.DATABASE_HOST }}
          database-user: ${{ secrets.DATABASE_USER }}
          database-name: ${{ secrets.DATABASE_NAME }}
          database-password: ${{ secrets.DATABASE_PASSWORD }}
